language: python
envlist=py25,py26,py27,py31,py32,py33,py34
python: 2.7
env:
  - TOX_ENV=py25
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py31
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
install:
  - pip install detox
script:
  - detox -e $TOX_ENV
