language: python
python: 3.4
env:
  matrix:
   - TOX_ENV=py26
   - TOX_ENV=py27
   - TOX_ENV=py32
   - TOX_ENV=py33
   - TOX_ENV=py34
   - TOX_ENV=flake8
install:
  - pip install tox
  - if test "$TOXENV" = py34 ; then pip install python-coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py34 ; then coveralls ; fi
